version: '3.1'

services:
  nnpia-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Pyth0n17!
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=Pyth0n17!
      - MYSQL_DATABASE=db

  nnpia-adminer:
    image: adminer
    ports:
      - 8081:8080